apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  ports:
  - name: wordpres
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31004
  selector:
    app: wordpress
  type: NodePort
status:
  loadBalancer: {}
