apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
spec:
  ports:
  - name: wordpress-mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  type: ClusterIP
status:
  loadBalancer: {}
