apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-persistent-volume
  labels:
    app: wordpress
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /wordpress-data
